### ISSUE TITLE
IOS No compile

### ISSUE THREAD

**Issue by rosell** [byrdsandbytes/capContactsDemo#3]
Hi!

When try to compile the APP on iOS, with Xcode Version 12.2 (12B45b), not work because appears the next errors:

* /Users/rosell/git/capContactsDemo/node_modules/@capacitor/ios/ios/Capacitor/Capacitor/Plugins/Permissions.swift:55:5
   - Switch must be exhaustive 
   - Add missing case: '.limited' 
   - Handle unknown values using "@unknown default"
* /Users/rosell/git/capContactsDemo/node_modules/@capacitor/ios/ios/Capacitor/Capacitor/Plugins/Permissions.swift:91:7
   - Switch must be exhaustive
   - Add missing case: '.ephemeral'
   - Handle unknown values using "@unknown default"

Steps:
- git clone https://github.com/byrdsandbytes/capContactsDemo.git
- cd capContactsDemo/
- npm install
- npx ionic build
- npx cap sync
- npx cap open ios 
- On Xcode press  Build and play button

**Comment by Idrimi** [comment]
@rosell demo app was outdated. Usually I keep the "community" branch updated:
Following steps should resolve your issue:

- git clone https://github.com/byrdsandbytes/capContactsDemo.git
- cd capContactsDemo/
- git checkout capacitor-community
- npm install (**better**: "npm ci")
- npx ionic build
- npx cap sync
- npx cap open ios
- On Xcode press Build and play button
